name: Next.js CI-CD

on:
  push:
    branches: [ main ]

env:
  SERVICE_NAME: jaynarol-blogs

  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  PHONITO_TOKEN: ${{ secrets.PHONITO_TOKEN }}
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_SA_KEY: ${{ secrets.GKE_SA_KEY }}
  GKE_CLUSTER: ${{ secrets.GKE_CLUSTER }}
  GKE_ZONE: ${{ secrets.GKE_ZONE }}

jobs:
  CI-CD-Flow:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Test Source with Jest
        run: |-
          npm ci
          npm test

      - name: Scan Source with Sonar
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: >
            -Dsonar.organization=vcodeth
            -Dsonar.projectKey=vCodeTH_jaynarol-blogs
            -Dsonar.language=js
            -Dsonar.sources=src/
            -Dsonar.exclusions=node_modules/**/*,coverage/**/*,src/styles/**/*,src/public/**/*,**/__test__/**/*,**/*.test.*,*.config.{js,json}
            -Dsonar.coverage.exclusions=**/*.tsx,**/__test__/*,**/*.test.*,*.config.{js,json}
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

      - name: Build NextJs
        id: build
        run: |-
          echo ::set-output name=IMAGE_NAME::"asia.gcr.io/${{ env.GKE_PROJECT }}/${{ env.SERVICE_NAME }}:$GITHUB_SHA"
          npm run build

      - name: Pack Artifact
        run: |-
          docker build \
                    --tag ${{ steps.build.outputs.IMAGE_NAME }} \
                    --build-arg GITHUB_SHA="$GITHUB_SHA" \
                    --build-arg GITHUB_REF="$GITHUB_REF" \
                    .

      - name: Scan Artifact
        uses: phonito/phonito-scanner-action@master
        with:
          image: ${{ steps.build.outputs.IMAGE_NAME }}
          phonito-token: '${{ env.PHONITO_TOKEN }}'

      - name: Connect GCP
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ env.GKE_PROJECT }}
          service_account_key: ${{ env.GKE_SA_KEY }}

      - name: Ship Artifact to GCR
        run: |-
          gcloud --quiet auth configure-docker
          gcloud container clusters get-credentials "${{ env.GKE_CLUSTER }}" --zone "${{ env.GKE_ZONE }}"
          docker push ${{ steps.build.outputs.IMAGE_NAME }}

      - name: Connect GKE
        uses: google-github-actions/get-gke-credentials@v0.2.1
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}
          credentials: ${{ env.GKE_SA_KEY }}

      - name: Deploy Artifact to GKE
        run: |-
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh
          helm upgrade "${{ env.SERVICE_NAME }}" .k8s/helm -f .k8s/helm-values/jaynarol-blogs-dev.yaml --set env.IMAGE=${{ steps.build.outputs.IMAGE_NAME }}