name: Node.js CI

on:
  push:
    branches: [ main ]

env:
  SERVICE_NAME: jaynarol-blogs
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  SA_EMAIL: ${{ secrets.GKE_SA_EMAIL }}
  SA_KEY: ${{ secrets.GKE_SA_KEY }}

jobs:
  CI-CD-Flow:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Test with Jest
        run: npm ci && npm test

      - name: Sonar Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=vcodeth
            -Dsonar.projectKey=vCodeTH_jaynarol-blogs
            -Dsonar.language=js
            -Dsonar.sources=src/
            -Dsonar.exclusions=node_modules/**/*,coverage/**/*,src/styles/**/*,src/public/**/*,**/__test__/**/*,**/*.test.*,*.config.{js,json}
            -Dsonar.coverage.exclusions=**/*.tsx,**/__test__/*,**/*.test.*,*.config.{js,json}
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info

      - name: Build NextJs
        run: npm run build

      - name: Connect GCP
        uses: google-github-actions/setup-gcloud@master
        with:
          version: '286.0.0'
          project_id: $PROJECT_ID
          service_account_email: $SA_EMAIL
          service_account_key: $SA_KEY

      - name: Pack Artifact
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "asia.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA"