name: Node.js CI

on:
  push:
    branches: [ main, dev ]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Test with Jest
        run: npm ci && npm test


      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=vcodeth
            -Dsonar.projectKey=vCodeTH_jaynarol-blogs
            -Dsonar.language=js
            -Dsonar.sources=src/
            -Dsonar.exclusions=node_modules/**/*,coverage/**/*,src/styles/**/*,src/public/**/*,**/__test__/*,**/*.test.*,*.config.{js,json}
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  Build:
    needs: Test
    runs-on: ubuntu-latest

    steps:
      - name: Prepare
        uses: actions/checkout@v2

      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Build
        run: npm ci && npm run build
